name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        go: [1.18.*, 1.19.*, 1.20.*, 1.21.*]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    name: Go ${{ matrix.go }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
    
      - name: Test
        run: go test -v ./...
